### PR TITLE
Fix issue 91

### PR DESCRIPTION
**Pull request by mmndaniel**
An attempt to fix [91](https://github.com/LavaMoat/snow/issues/91), using approach c which I mentioned [here](https://github.com/LavaMoat/snow/issues/91#issuecomment-1597465364)...

### CODE REVIEW

**Comment by weizman** [comment]
Thanks for the PR @mmndaniel ! Highly appreciated 🙏 

I'm not sure what the intent here is, but I'm pretty sure something is missing.

According to MDN, the API expects a node rather than a string. Also, the variable you use inside the try-catch block does not exist.

Without the try-catch you'd see this solution doesn't work currently, do you mind explaining again the logic you had in your mind behind this attempt please?

**Comment by mmndaniel** [comment]
Ah shit, sorry, was coding in a rush! Anyway, the idea is to use `XMLSerializer` to normalize the HTML and prevent namespace confusion (that leads to the mXSS bug). See [section 5.2 here](https://cure53.de/fp170.pdf).

**Comment by weizman** [comment]
yo @mmndaniel check out #108

**Comment by mmndaniel** [comment]
from the paper linked above:
```
attacks can be upgraded
to allow recursive mutation – making double-, triple- and
further multiply-encoded escapes and entities useful in the
attack scenario, immediately when multiple innerHTMLaccess to the same element takes place.
```
So I'm afraid single `innerHTML` assignment isn't enough (I will try to implement this type of attack soon). It MIGHT be possible to re-assign until two consecutive assignments result the same `childNodes.length`, but this approach a. have performance drawbacks and b. possibly vulnerable, if an attacker could craft a payload that mutates only after 3 consecutive assignments (not sure if that's possible, but the with complexity of (X/Math/HT)ML and SVG ser/de, who knows).

**Comment by mmndaniel** [comment]
I don't think it's the way forward because it's possible to implement mutation attack without any "special" tags, just svg, style, etc are enough. See [this PR](https://github.com/cure53/DOMPurify/pull/495), I suspect that's the right approach to address it.

**Comment by weizman** [comment]
ending up with #123

**Pull request closed without merging**
